### ISSUE TITLE
Back arrow is broken in AMUST page

### ISSUE THREAD

**Issue by giumas** [OSHydro/OSHydro.github.io#1]
To recreate:

- Open https://www.oshydro.org/projects/amust.html
- Click on the back arrow at the bottom page.

**Comment by giumas** [comment]
Same issue on https://www.oshydro.org/projects/globe.html

**Comment by giumas** [comment]
And https://www.oshydro.org/projects/CruiseTools.html

**Comment by monocilindro** [comment]
Fixed. The broken link addressed to a markdown document instead of to  project.html
